name: Escalate GitHub Issue

on:
  issues:
    types:
      - labeled
      - opened
      - synchronize
      - edited
  schedule:
    - cron: "*/5 * * * *"

jobs:
  escalate:
    runs-on: ubuntu-latest

    steps:
    - name: Check Issue Label and Status
      env:
        GH_TOKEN: ${{ github.token }}
      id: check_label_status
      run: |
        repository="Shubham9t9/repo"
        username="Shubham9t9"
        
        # Fetch and assign issues
        for issue in $(gh issue list --repo "$repository" --json labels,number,created --label "pager-duty" --jq '.[] | select((.labels[] | .name == "pager-duty") and (.created_at | fromdateiso8601 < (now - 60))) | .number'); do
            gh issue edit "$issue" --assignee "$username"
            echo "Assigned issue #$issue to $username"
        done
