name: Escalate GitHub Issue

on:
  issues:
    types:
      - labeled
      - opened
      - synchronize
      - edited
  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  escalate:
    runs-on: ubuntu-latest

    steps:
    - name: Check Issue Label and Status
      env:
        GH_TOKEN: ${{ github.token }}
      id: check_label_status
      run: |
        repository="https://github.com/Shubham9t9/repo.git"
        username="Shubham9t9"
        issue_data=$(gh issue list --repo Shubham9t9/repo --json labels,number,createdAt)
        echo "$issue_data"
        # Fetch and assign issues
        for issue in $(gh issue list --repo "$repository" --json labels,number,createdAt --label "pager-duty" --jq '.[] | select((.labels[] | .name == "pager-duty") and (.createdAt | fromdateiso8601 < (now - 60))) | .number'); do
            gh issue edit "$issue" --add-assignee "$username"
            echo "Assigned issue #$issue to $username"
        done
