name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Validate Issue Reference
      run: |
        set -e
        
        # Get the pull request body
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        
        # Check if the pull request body contains "Fixes" or "Resolves" keywords
        if echo "$PR_BODY" | grep -Ei 'fixes #[0-9]+|resolves #[0-9]+'; then
          echo "Issue reference found in the pull request body."
        else
          echo "No valid issue reference found in the pull request body."
          exit 1
        fi
